language: cpp
dist:     bionic
os:       linux

addons:
  sources:
    - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
  apt:
    packages: &base_packages
    - cmake
    - libblas-dev
    - liblapack-dev

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install


matrix:
  include:
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
            - gfortran-7
            - libscalapack-mpich-dev
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - *base_packages
            - g++-7
            - gfortran-7
            - libscalapack-mpich-dev



before_install:
  - env
  - mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}
script:
  - echo $PWD
  - bash ./scripts/build_travis.sh
